version: '3'

networks:
  dbnet:
  redisnet:
  webnet:

services:
  db:
    image: postgres:15-alpine
    container_name: nextcloud_pg
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-nextcloud}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:?}"
      POSTGRES_DB: "${POSTGRES_DB:-nextcloud}"
    networks:
      - dbnet

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - redisnet

  app:
    build:
      context: ./nextcloud
      dockerfile: Dockerfile
      args:
        IMAGE_VERSION: 25
    container_name: nextcloud
    restart: always
    volumes:
      - ${NEXTCLOUD_HTML:-html}:/var/www/html
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: "${POSTGRES_USER:-nextcloud}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:?}"
      POSTGRES_DB: "${POSTGRES_DB:-nextcloud}"
      REDIS_HOST: redis
      PHP_MEMORY_LIMIT: "${PHP_MEMORY_LIMIT:-512M}"
      PHP_UPLOAD_LIMIT: "${PHP_UPLOAD_LIMIT:-512M}"
    depends_on:
      - db
      - redis
    networks:
      - dbnet
      - redisnet
      - webnet

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    ports:
      - 8080:80
    depends_on:
      - app
    networks:
      - default
      - webnet

volumes:
  db:
