services:
  protonvpn:
    image: qmcgaw/gluetun:v3
    container_name: protonvpn
    environment:
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY:?}
      PORT_FORWARD_ONLY: on
      VPN_PORT_FORWARDING: on
      VPN_PORT_FORWARDING_PROVIDER: protonvpn
      VPN_PORT_FORWARDING_STATUS_FILE: /protonvpn-port/protonvpn-port
      SERVER_COUNTRIES: ${VPN_COUNTRIES:?}
      VPN_PORT_FORWARDING_DOWN_COMMAND: /bin/rm /protonvpn-port/protonvpn-port
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./protonvpn/gluetun:/gluetun
      - port:/protonvpn-port
    ports:
      - 9091:9091

  transmission:
    build:
      context: ./transmission
      dockerfile: Dockerfile
      args:
        TRANSMISSION_VERSION: "${TRANSMISSION_VERSION:-latest}"
    container_name: transmission
    environment:
      PUID: ${LSIO_PUID:-1000}
      PGID: ${LSIO_PGID:-1000}
      TZ: ${LSIO_TZ:-Europe/Paris}
      USER: ${TRANSMISSION_USER:-}
      PASS: ${TRANSMISSION_PASSWORD:-}
      TR_AUTH: "${TRANSMISSION_USER}:${TRANSMISSION_PASSWORD}"
      TRACKERS_URL: ${TRANSMISSION_TRACKERS_URL:-}
      TORRENT_DONE: "${TRANSMISSION_TORRENT_DONE:-}"
    userns_mode: host
    network_mode: service:protonvpn
    volumes:
      - ${TRANSMISSION_DOWNLOADS:-./downloads}:/downloads
      - ${TRANSMISSION_CONFIG:-./config}:/config
      - port:/protonvpn-port:ro
    healthcheck:
      test: /healthcheck.sh
      interval: 50s
      timeout: 5s
      retries: 3
    depends_on:
      protonvpn:
          condition: service_healthy
    restart: unless-stopped

volumes:
  port:
