services:
  protonvpn:
    image: ghcr.io/tprasadtp/protonwire:${PROTONVPN_VERSION:-7.5.2}
    entrypoint: ["/bin/sh", "-c"]
    command: "/config/init.sh"
    container_name: protonvpn
    environment:
      PROTONVPN_SERVER: ${PROTONVPN_SERVER:-}
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY:-}
      IPCHECK_INTERVAL: 0
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.conf.all.rp_filter: 2
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - type: tmpfs
        target: /tmp
      - ./protonvpn:/config:ro
      - port:/protonvpn-port
    healthcheck:
      test: /config/protonvpn-healthcheck.sh
      interval: 40s
      timeout: 5s
      retries: 3
    ports:
      - 9091:9091

  transmission:
    image: lscr.io/linuxserver/transmission:${TRANSMISSION_VERSION:-latest}
    container_name: transmission
    environment:
      PUID: ${LSIO_PUID:-1000}
      PGID: ${LSIO_PGID:-1000}
      TZ: ${LSIO_TZ:-Europe/Paris}
      USER: ${TRANSMISSION_USER:-}
      PASS: ${TRANSMISSION_PASSWORD:-}
      TRACKERS_URL: ${TRANSMISSION_TRACKERS_URL:-}
    userns_mode: host
    network_mode: service:protonvpn
    volumes:
      - ${TRANSMISSION_DOWNLOADS:-./downloads}:/downloads
      - ${TRANSMISSION_CONFIG:-./config}:/config
      - port:/protonvpn-port:ro
      - ./transmission:/custom-cont-init.d:ro
    depends_on:
      protonvpn:
          condition: service_healthy
    restart: unless-stopped

volumes:
  port:
