services:
  protonvpn:
    build:
      context: ./protonvpn
      dockerfile: Dockerfile
      args:
        WIREGUARD_VERSION: "${WIREGUARD_VERSION:-latest}" 
    container_name: protonvpn
    environment:
      PUID: ${LSIO_PUID:-1000}
      PGID: ${LSIO_PGID:-1000}
      TZ: ${LSIO_TZ:-Europe/Paris}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.conf.all.rp_filter: 2
      net.ipv6.conf.all.disable_ipv6: 1
      net.ipv4.conf.all.src_valid_mark: 1
    volumes:
      - ./protonvpn/config:/config
      - ./protonvpn:/protonvpn:ro
      - port:/protonvpn-port
      - /lib/modules:/lib/modules
    healthcheck:
      test: /custom-services.d/protonvpn-healthcheck.sh
      interval: 40s
      timeout: 5s
      retries: 3
    ports:
      - 9091:9091

  transmission:
    image: lscr.io/linuxserver/transmission:${TRANSMISSION_VERSION:-latest}
    container_name: transmission
    environment:
      PUID: ${LSIO_PUID:-1000}
      PGID: ${LSIO_PGID:-1000}
      TZ: ${LSIO_TZ:-Europe/Paris}
      USER: ${TRANSMISSION_USER:-}
      PASS: ${TRANSMISSION_PASSWORD:-}
      TRACKERS_URL: ${TRANSMISSION_TRACKERS_URL:-}
    userns_mode: host
    network_mode: service:protonvpn
    volumes:
      - ${TRANSMISSION_DOWNLOADS:-./downloads}:/downloads
      - ${TRANSMISSION_CONFIG:-./config}:/config
      - port:/protonvpn-port:ro
      - ./transmission:/custom-cont-init.d:ro
    depends_on:
      protonvpn:
          condition: service_healthy
    restart: unless-stopped

volumes:
  port:
